[package]
name = "english-study"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ass = "1.1.2"
ass_parser = "0.1.4"
axum = "0.7.5"
encoding_rs = "0.8.34"
regex = "1.10.6"
tantivy = "0.22.0"
